---
title: "Leaflet Building"
output: html_notebook
---

```{r setup, message = FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)
library(tidyquant)
library(timetk)
```

# let's build a map of the earth

```{r}
library(rnaturalearth)
library(rgeos)

world <- ne_countries(type = "countries", returnclass = 'sf') #sp is other type

# For the sake of brevity, let's look at just the first 6 countries
world %>%
  select(name, gdp_md_est, pop_est, lastcensus, economy, subregion) %>% 
  slice(1:6)

#If you want to peek at the longitude and latitude, use world$geometry
class(world$geometry)
```



```{r}
library(leaflet)

# Create a palette with different shades of blue for different
# GDP estimates.

gdpPal20 <- colorQuantile("Blues", 
                        world$pop_est, 
                        n = 20)

gdpPal10 <- colorQuantile("Blues", 
                        world$pop_est, 
                        n = 10)

gdpPal5 <- colorQuantile("Blues", 
                        world$pop_est, 
                        n = 5)
```


```{r}
# Make a popup object.
# Notice we're referencing the column names with the '$', same as we would with a non-spatial dataframe.
economyPopup <- paste0("<strong>Country: </strong>", 
                world$name, 
                "<br><strong>Last Census: </strong>", 
                 world$lastcensus)
```



```{r}
 # Build our leaflet map object.

leaf_world_economy <- 
  leaflet(world) %>%
  addProviderTiles("CartoDB.Positron") %>% 
  setView(lng =  20, lat =  15, zoom = 2) %>%
      addPolygons(stroke = FALSE, 
                  smoothFactor = .2, 
                  fillOpacity = .8, 
                  color = ~gdpPal10(pop_est), 
                  layerId = ~name, 
                  popup = economyPopup)

# Display that object below.

leaf_world_economy
```



```{r}
# Let's build a dataframe to store these ticker symbols, country names and YTD numbers.

tickers <-  c("ECH", "EDEN", "EFNL", "EIDO", "EIRL", "EIS", "ENOR", "ENZL", 
"EPHE", "EPOL", "EPU", "ERUS", "EWA", "EWC", "EWD", "EWG", "EWH", 
"EWI", "EWJ", "EWK", "EWL", "EWM", "EWN", "EWO", "EWP", "EWQ", 
"EWS", "EWT", "EWU", "EWW", "EWY", "EWZ", "EZA", "FXI", "ICOL", 
"INDA", "KSA", "QAT", "THD", "TUR", "UAE")


name <-   c("Chile", "Denmark", "Finland", "Indonesia", "Ireland", "Israel", 
"Norway", "New Zealand", "Philippines", "Poland", "Peru", "Russia", 
"Australia", "Canada", "Sweden", "Germany", "Hong Kong", "Italy", 
"Japan", "Belgium", "Switzerland", "Malaysia", "Netherlands", 
"Austria", "Spain", "France", "Singapore", "Taiwan", "United Kingdom", 
"Mexico", "Korea", "Brazil", "South Africa", "China", "Colombia", 
"India", "Saudi Arabia", "Qatar", "Thailand", "Turkey", "United Arab Emirates"
)

etf_ticker_country <- data_frame(tickers, name)

etf_ticker_country
```

 

```{r}

# Using getSymbols to import the ETF price histories will take a minute or two or 
# five - 41 time series is a lot of data. 


etf_prices_ytd <- 
  getSymbols(etf_ticker_country$tickers, 
             auto.assign = TRUE, 
             from = "2018-01-01", 
             warnings = FALSE) %>%
  map(~Ad(get(.))) %>% 
  reduce(merge) %>% 
  `colnames<-`(etf_ticker_country$name) %>%
  tk_tbl(preserve_index = TRUE, rename_index = "date") %>% 
  na.omit() %>% 
  gather(name, price, -date) %>% 
  group_by(name) %>%
  summarise(ytd = round(((last(price) - first(price))/first(price) * 100), 2))

```


```{r}

etf_ticker_name_ytd <- merge(etf_prices_ytd, etf_ticker_country, by = "name", all.x = TRUE)

# take a look at the merged object
etf_ticker_name_ytd
```


```{r}
# Once we run this line of code, our ticker symbols and ytd numbers will be added
# to the simple features dataframe.

world_etf <- merge(world, etf_ticker_name_ytd, by = "name", all.x = TRUE)

world_etf %>% 
  select(name, ytd, tickers) %>% 
  na.omit() %>% 
  head()


```



```{r}
# Create a palette with different shades of red yellow green for different
# year-to-date performances. 

ytdPal_RdYlGn <- colorQuantile("RdYlGn", 
                               world_etf$ytd, 
                               n = 20)

ytdPal_Blue <- colorQuantile("Blues", 
                             world_etf$ytd, 
                             n = 20)
```


Let’s also have the popup display the exact year-to-date performance percentage for any detail-oriented users.

```{r}
# Create a popup that displays the year-to-date performance.

ytdPopup <- paste0("<strong>Country: </strong>", 
                world_etf$name,
                "<br><strong> Year-to-date: </strong>", 
                world_etf$ytd, "%")
```
 


```{r}

leaf_world_etf <- leaflet(world_etf) %>%
  addProviderTiles("CartoDB.Positron") %>% 
  setView(lng =  20, 
          lat =  15, 
          zoom = 2) %>%
      addPolygons(stroke = FALSE, 
                  smoothFactor = 0.2, 
                  fillOpacity = .7,      
      color =~ytdPal_RdYlGn(ytd), 
      # Important line of code next
      layerId = ~tickers, 
      popup = ytdPopup)

leaf_world_etf
```


